global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'con-gzx.node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.2.1.1:9100']

  - job_name: 'con-gzx.nginx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.2.2.8:9913']

  - job_name: 'con-gzx.nginx-vts-exporter'
    scrape_interval: 15s
    metrics_path: /status/format/prometheus
    static_configs:
      - targets: ['10.2.2.8:11050']

  - job_name: 'con-gzx.cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'con-gzx.wgexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.2.2.1:9586']

  - job_name: 'or-br1-gzx.node-exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.2.1.23:9100']

  - job_name: 'or-br2-gzx.node-exporter'
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: ['10.2.1.24:9100']










  - job_name: 'node-exporter-or-de3-arm-gzx'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.2.1.22:9100']
      
  - job_name: 'pihole-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.2.2.1:9617']

  - job_name: 'minecraft-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.2.2.1:8000']